# Generated by Django 2.2.4 on 2019-08-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('details_about', models.CharField(max_length=100)),
                ('ifnotin', models.CharField(max_length=100)),
                ('franchise_favour', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('specs_detail', models.CharField(max_length=300)),
            ],
        ),
    ]
