# Generated by Django 2.2.4 on 2019-08-12 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccwork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='specs_detail',
        ),
    ]
