# Generated by Django 2.2.4 on 2019-08-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccwork', '0002_remove_contactinfo_specs_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='specs_detail',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
